AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: AWS SAM template that creates 3 lambda function which retrives application configurarion details from Amazon EC2 Systems Manager Parameter Store

Outputs:
    lambdaSSMgetparamFunction:
      Description: "Get Parameter Lambda Function ARN"
      Value: !GetAtt lambdaSSMgetparamFunction.Arn

    lambdaSSMgetparamsFunction:
      Description: "Get Parameters Lambda Function ARN"
      Value: !GetAtt lambdaSSMgetparamsFunction.Arn

    lambdaSSMgetparamsWithDecryptionFunction:
      Description: "Decrypted Get Parameters Lambda Function ARN"
      Value: !GetAtt lambdaSSMgetparamsWithDecryptionFunction.Arn

Resources:
  AppUrl:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "appURL"
      Type: "String"
      Value: "http://aws.amazon.com"
      Description: "SSM Parameter for appURL"
  PageToken:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "pageToken"
      Type: "String"
      Value: "ab0460a2-c346-11e7-abc4-cec278b6b50a"
      Description: "SSM Parameter for pageToken"

  LambdaSSMExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      RoleName: "ssm-lambda-role"

  LambdaRolePolicies:
    Type: AWS::IAM::Policy
    Properties:
        PolicyName: lambda-ssm-kms-policy
        PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action: 
                    - ssm:GetParameter
                    - ssm:GetParameters
                Resource:
                    - !Join
                        - ''
                        - - 'arn:aws:ssm:'
                          - !Ref AWS::Region
                          - ':'
                          - !Ref 'AWS::AccountId'
                          - ":parameter/pageToken"

                    - !Join
                        - ''
                        - - 'arn:aws:ssm:'
                          - !Ref AWS::Region
                          - ':'
                          - !Ref 'AWS::AccountId'
                          - ":parameter/appURL"
              #### Uncomment the below block to retrieve decrypted parameters from SSM Parameter store.
              #### Update your KMS key
              # -
              #   Effect: Allow
              #   Action: 
              #       - kms:Decrypt
              #   Resource: [
              #     # update the below key to your KMS key
              #     # arn:aws:kms:<region>:<AccountId>:key/bd13960c-f1f4-454f-850b-016ba3b4f905
              #     ]
              #####
              -
                Effect: Allow
                Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        Roles:
          -
            Ref: LambdaSSMExecutionRole
  
  lambdaSSMgetparamFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getParameter.handler
      Runtime: nodejs6.10
      CodeUri: s3://<bucket_name>/lambda_function.zip
      Description: Lambda function that retrieves a specific configuration from Amazon EC2 Systems Manager Parameter Store
      Role: 
        Fn::GetAtt: 
          - "LambdaSSMExecutionRole"
          - "Arn"
      FunctionName: lambda-ssm-getparam-function
  
  lambdaSSMgetparamsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getParameters.handler
      Runtime: nodejs6.10
      CodeUri: s3://<bucket name>/lambda_function.zip
      Description: Lambda function that retrieves a list of configurations from Amazon EC2 Systems Manager Parameter Store
      Role: 
        Fn::GetAtt: 
          - "LambdaSSMExecutionRole"
          - "Arn"
      FunctionName: lambda-ssm-getparams-function
  
  lambdaSSMgetparamsWithDecryptionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: getParametersDecrypted.handler
      Runtime: nodejs6.10
      CodeUri: s3://<bucket name>/lambda_function.zip
      Description: Lambda function that retrieves a list of decrypted configuration from Amazon EC2 Systems Manager Parameter Store
      Role: 
        Fn::GetAtt: 
          - "LambdaSSMExecutionRole"
          - "Arn"
      FunctionName: lambda-ssm-getparams-with-decryption-function
